language: python

stages:
  - lint
  - test
  - build
# TODO: needs additional setup
#  - deploy

before_install:
  - pip install codecov

install:
  - pip install .

before_script:
  - cd tests/config
  - bash create_ssl_certs.sh -h localhost -i 127.0.0.1
  - cd ../..
  - docker-compose -f tests/config/docker-compose.yml down
  - docker-compose -f tests/config/docker-compose.yml up -d
  - sleep 40
  - "curl -u admin:admin 'http://127.0.0.1:9000/api/search/universal/relative?query=test&range=5&fields=message' || true"

script:
  - python setup.py test

after_script:
  - docker-compose -f tests/config/docker-compose.yml down

after_success:
  - codecov

jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: "pypy2.7-5.10.0"
    - python: "pypy3.5-5.10.0"
    - stage: lint
      name: "pylint"
      python:
        - 3.6
      before_script: skip
      script:
        - python setup.py lint || exit $(($? & 35))
      after_script: skip
    - name: "twine check"
      python:
        - 3.6
      before_install:
        - pip install docutils twine
      before_script:
        - python setup.py sdist
      script:
        - twine check dist/*
      after_script: skip
    - stage: build
      name: "sdist"
      python:
        - 3.6
      before_script: skip
      script:
        - python setup.py sdist
      after_script: skip
    - name: "bdist_wheel"
      python:
        - 3.6
      install:
        - pip install . wheel
      before_script: skip
      script:
        - python setup.py bdist_wheel
      after_script: skip
    - stage: deploy
      deploy:
        python:
          - 3.6
        provider: pypi
        user: nklapste
        password:
          secure: Ryu87EzCW+k/quo2yC05cejU29zo9Xwlv9f2zxwMhCDRwMGt4GCSJ4zR7GXvYT0B5H6S+Y+gCxTmSSA53V1aRvCX0A42i6P9jef2yWR34aYe0+lmYwwW1wNKo/SLD1x5cXw59m5pcVGPvAVY9aQ88DwR9gn6aMr76A6LJet/ykY=
        on:
          tags: true
          branch: master
          repo: severb/graypy
        distributions: "sdist bdist_wheel"
