language: python

stages:
  - lint
  - test
  - build
# TODO: needs additional setup
#  - deploy

before_install:
  - pip install codecov

install:
  - pip install .

before_script:
  - cd tests/config
  - bash create_ssl_certs.sh -h localhost -i 127.0.0.1
  - cd ../..
  - docker-compose -f tests/config/docker-compose.yml down
  - docker-compose -f tests/config/docker-compose.yml up -d
  - sleep 40
  - "curl -u admin:admin 'http://127.0.0.1:9000/api/search/universal/relative?query=test&range=5&fields=message' || true"

script:
  - python setup.py test

after_script:
  - docker-compose -f tests/config/docker-compose.yml down

after_success:
  - codecov

jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: "pypy2.7-5.10.0"
    - python: "pypy3.5-5.10.0"
    - stage: lint
      python:
        - 3.6
      before_script: skip
      after_script: skip
      script:
        - python setup.py lint || exit $(($? & 35))
    - stage: build
      name: "sdist"
      python:
        - 3.6
      before_script: skip
      script:
        - python setup.py sdist
      after_script: skip
    - name: "bdist_wheel"
      python:
        - 3.6
      install:
        - pip install . wheel
      before_script: skip
      script:
        - python setup.py bdist_wheel
      after_script: skip
    - stage: deploy
      deploy:
        python:
          - 3.6
        provider: pypi
        user: nklapste
        password:
          secure: Rx1M/SfoBIWV8RMjBrsojluQoGk6g99TEk1FsbAsPF3Mr3C8BdaKPLW3VCV44ZmL1UBQg0Okwh+TupOBRBkpyeJtTjxNbnwvJtmKAfjgvYwbw4tYagJZlNU5wOKRNKF/4gMRlzdj4B7/upn8fenUSEK33MomxawV/5/o1c/znB5RUZCyBv55nsN6IVTwpGXv8OWcM2x/6UHMpHqyCQEXvnI+mwxoVkb9TpoTLJoWH+Hr9hmHFuZpmGvXXtn7Z6umM2/KEN5V+Cv4pDUnoFpmF6jlkw/89zX3Bd2e8lVBLwV2TRY59Y4Fi0iK4s0nZLsUVvvLersjwZ7a6c+rtu5q60/AjNr+FHrZifZ0vljrgHrrRSzCYoODBYteLUQLAwR/OXgtrG/3LX8mt9mMLaO5SxF7OmDlvNWabWmKIuuiGsMFB39wRd3NMBJC8e9JmLP+kI3Y+AGAtrmktIUtxvIAhd/JQn5pci325R1DkObhOAxSInvVo53z2xuaNMud2cvNDIzTuzMdBFxAoA67oLHEmfMpVIr8YtXwgBATxQ4GO9uCxT4mbCzUcHIRJhjMFyY15NbyASOeIP85JOCOiU9WjLC/NKdpazapcc6vgfgEvcLbhwA+QupJoyOAQmzTXfC7eOKishj8Oi0rsbtNa6ozEKDKW/SUeBj9PO2NJESzbLQ=
        on:
          tags: true
          branch: master
          repo: severb/graypy
        distributions: "sdist bdist_wheel"
